### ISSUE TITLE
PA_IL_CL?

### ISSUE THREAD

**Issue by ybsu** [ruhollahpython/proximity#10]
Hello Sir, I studied your article due to research needs and downloaded the code from 'github', I am also a programmer beginner,  I have studied your codes for several days, I have a question,I have not understood  the difference of the three functions: PA_IL_CL1,PA_IL_CL2 and PA_IL_CL3,what is the meaning of their returned values ?  which functions are implemented by the three functions ?

I would greatly appreciate it if you could help me.I look forward to hearing from your soon.
your sincerely
Tom

**Comment by ybsu** [comment]
Sir, would you mind me asking you one more question? Where is the function of fair_R3,I have not found it .

**Comment by roamiri** [comment]
I added a develop and master branch on the project. The master branch is stable. Please use the master branch. Also:
1- I added the main file so you know what file you should run. There is a parallel flag as the input of the main file. Put parallel=0 if you want to run the code in a single thread or put it as one if you're going to run the code as parallel.

2- I did a bugfix in SINR_FUE_2.m

3- Now there is just one PA_IL_CL file. This is the main power allocation file which can run as independent learning (CL=0) or cooperative learning (CL=1).
