### ISSUE TITLE
my inssues

### ISSUE THREAD

**Issue by githublzb** [ruhollahpython/proximity#12]
![1111](https://user-images.githubusercontent.com/28134131/54690162-c6260b80-4b5b-11e9-88e1-081965829df6.jpg)

**Comment by githublzb** [comment]
I used the code to reproduce the article. But the results are different from those given in the article. Please help me solve the problem.

**Comment by roamiri** [comment]
I think you first need to run it multiple times and average the results.

**Comment by sanabel99** [comment]
> ![1111](https://user-images.githubusercontent.com/28134131/54690162-c6260b80-4b5b-11e9-88e1-081965829df6.jpg)

I need some help regarding the code, can you please share your contact info?
