### ISSUE TITLE
Variable Values and Description in PA_IL_CL.m and main.m

### ISSUE THREAD

**Issue by us2020** [ruhollahpython/proximity#14]
Dear Author 
can you please guide about the input variables as there is no description available in code. 
Or if you have step by step instructions to run code.

**Comment by roamiri** [comment]
femtocellPermutation: the number of permutations which is used to generate different sequences of adding femtocells. After creating for example 100 permutations, we average over the results.NumRealization: simply number of times we create a channel to generate small scale fading.saveNum: stands for the permutation number. Also, I have used it to differentiate between final saved files.CL: if it'ss set to 1, the learning is cooperative and if it's set to 0, the learning is independent.

**Comment by Azhe9510** [comment]
Dear Author：
1.How to define "saveNum"  “femtocellPermutation” in PA_IL_CL.m (lines  7th and  lines 90th respectively)  could you give an example?

**Comment by roamiri** [comment]
They are set in the main.m when calling runForAll function.

**Comment by vamsnaidu** [comment]
how to define femtocellpermutation and savenum ?

**Comment by roamiri** [comment]
start from main.m file and you will understand it.
