### ISSUE TITLE
the .mat files 

### ISSUE THREAD

**Issue by zhuwenxing** [ruhollahpython/proximity#7]
It seems that there are many .mat files missing and load(filename) always error because of that.

**Comment by roamiri** [comment]
.mat files are the outputs of the main program. After producing them, you
can feed them to the files in drawplots folder for analysis and producing
graphs!

**Comment by zhuwenxing** [comment]
So which program or function  should I run to product .mat files ? if by running function ,what is  the input of function  (default or decided by yourself)?

**Comment by roamiri** [comment]
*prallel_R_pro* is the file that you run in order for parallel
implementation. In the *runForAll* function, you will choose which power
allocation ( files which start with *PA*) policy to run. The output of the
program is set in the last line of power allocation files which produces
.mat files.

**Comment by bingruo** [comment]
Dear athor:
save(sprintf('results/pro_%d_%d_%d.mat',Npower, fbsCount, saveNum),'QFinal')
There was an error when I ran this line of code, so I don't quite understand some of the.mat files in there.
