### ISSUE TITLE
R_18_noshare/pro_%d_%d.mat

### ISSUE THREAD

**Issue by wlglixin** [ruhollahpython/proximity#8]
s = sprintf('oct10/R_18_noshare/pro_%d_%d.mat',i,j);
I got a problem. I don't know which .m file will output "oct10/R_18_noshare/pro_%d_%d.mat".please~~

**Comment by roamiri** [comment]
The s = sprintf('oct10/R_18_noshare/pro_%d_%d.mat',i,j); command loads the saved files that are saved earlier. The save commands are in power allocation related files such as PA_IL_CL.m.
