### ISSUE TITLE
Dear sir

### ISSUE THREAD

**Issue by minda-yang** [ruhollahpython/proximity#9]
Hello Sir, I studied your article due to research needs and downloaded the code from 'github', but I encountered a lot of problems during the run so that it didn't run completely. I am a programmer beginner. In fact, I have been exploring the code for three days. It contains a lot of commented code and I don’t know when to use them.On the other hand, I can't find ‘R3-share’ or ‘noshare’ in the drawing code file, etc.how to generate some .m file, etc.
I would greatly appreciate it if you could help me.I look forward to hearing from your soon.

your sincerely
minda

**Comment by roamiri** [comment]
Hi,

I am really sorry to get back to you late. I have been developing the code
recently and it is not very well organized. I will commit a new version in
a few days with some documentation that you can use.

Regards,
Roohollah

**Comment by minda-yang** [comment]
Thank you sir,I thought that you would not reply, so that I have not noticed that you have already replied to me.It is my pleasure to get your reply.I will continue to pay attention to your development.Hope you have a happy holidays!

Best wishes
minda

**Comment by roamiri** [comment]
I apologize that took me a long time to respond properly. I added a develop and master branch on the project. The master branch is stable. Please use the master branch. Also:
1- I added the main file so you know what file you should run. There is a parallel flag as the input of the main file. Put parallel=0 if you want to run the code in a single thread or put it as one if you're going to run the code as parallel.

2- I did a bugfix in SINR_FUE_2.m

3- Now there is just one PA_IL_CL file. This is the main power allocation file which can run as independent learning (CL=0) or cooperative learning (CL=1). 

Please do not hesitate to contact me if you have any questions.

**Comment by minda-yang** [comment]
Thank you for all your assistance.
